
function fish_user_key_bindings
  bind \cr 'peco_select_history (commandline -b)'
end

### azure completion - begin. generated by omelette.js ###
function _azure_complette
  azure --compfish --compgen (count (commandline -poc)) (commandline -pt) (commandline -pb)
end
complete -f -c azure -a '(_azure_complette)'
### azure completion - end ###

function fish_prompt
  echo -n (set_color cyan)(prompt_pwd) (set_color green)'❯'
 
  # Git
  set last_status $status
  printf '%s ' (__fish_git_prompt)
  set_color normal
end

set fish_theme agnoster

# Terraform
export PATH="$HOME/.tfenv/bin:$PATH"
alias tf="terraform"
alias tfp="terraform plan"
alias tfv="terraform validate"
alias tff="terraform fmt -recursive"

azure --completion-fish | source

export ARM_SUBSCRIPTION_ID=""
export ARM_CLIENT_ID=""
export ARM_CLIENT_SECRET=""
export ARM_TENANT_ID=""

# goenv
set -x GOENV_ROOT $HOME/.goenv
set -x PATH $GOENV_ROOT/bin $PATH
eval (goenv init - | source)
set -x PATH $GOPATH/bin $PATH

set -gx PATH $PATH $HOME/.krew/bin
